name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Trigger Jenkins Build
      run: |
        JENKINS_URL="http://localhost:8080/"
        JOB_NAME="Lab1"
        USER="vezyn4ik"
        API_TOKEN="113969ac729c08c34cdb9263bfa16725ed"

        curl -u "$USER:$API_TOKEN" "$JENKINS_URL/job/$JOB_NAME/build?token=your-jenkins-job-token"

